# Generated by Django 4.1 on 2024-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("semester", models.IntegerField()),
                ("start_date", models.DateField()),
                ("average", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
