# Generated by Django 4.1 on 2023-12-24 12:33

from django.db import migrations, models

"""
Diese Datei wurde durch diesen Befehl generiert  -> manage.py makemigrations 
Dadurch sind noch keine Tatsächlichen Änderungen in der Datenbank passiert es wurde nur diese Datei erzeugt.

Um die Änderungen zu übertragen, muss noch dieser Befehl ausgeführt werden -> manage.py migrate
"""

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            # Jede generierte Tabelle hat als erstes Feld immer eine id. Das wird automatisch so generiert!
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice_title", models.CharField(max_length=80)),
                ("notice_text", models.TextField()),
                ("pub_start", models.DateTimeField()),
                ("pub_end", models.DateTimeField()),
            ],
        ),
    ]
